name: RIR update nightly cronjob

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install curl
        run: |
          sudo apt-get install -y curl

      - name: Running backup script
        run: |
          sudo bash .github/backup.sh ${GITHUB_WORKSPACE}

      - name: Commit RIR changes
        uses: EndBug/add-and-commit@v8
        with:
          author_name: Github Action Bot
          author_email: noreply@github.com
          message: 'Nightly update of raw RIR changes based on registration'
          add: 'data/*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
